image: nexus.gretzki.ddns.net:10501/alpine-dotnet-sdk:latest

variables:
  OBJECTS_DIRECTORY: obj
  NUGET_PACKAGES_DIRECTORY: .nuget
  SOURCE_CODE_PATH: LibPing.Net

cache:
  key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
  paths:
    - $SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY
  policy: pull-push

before_script:
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  script:
    - dotnet build --no-restore

tests:
  stage: test
  script:
    - dotnet test --no-restore

securityanalysis:
  stage: test
  script:
    - security-scan ./LibPing.Net.sln

deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
  stage: deploy
  script:
    - dotnet build -c Release --no-restore
    - dotnet pack LibPing.Net/LibPing.Net.csproj -c Release --no-restore -o .
    - dotnet nuget push "*.nupkg" --skip-duplicate -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    - dotnet nuget push "*.nupkg" --skip-duplicate -k $NEXUS_NUGET_API_KEY -s https://nexus.gretzki.ddns.net/repository/nuget-hosted/
