image: nexus.gretzki.ddns.net:10501/alpine-dotnet-sdk:latest

variables:
  OBJECTS_DIRECTORY: obj
  NUGET_PACKAGES_DIRECTORY: .nuget
  SOURCE_CODE_PATH: LibPing.Net

cache:
  key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
  paths:
    - $SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY
  policy: pull-push

before_script:
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  script:
    - dotnet build --no-restore

tests:
  stage: test
  script:
    - dotnet test --no-restore

securityanalysis:
  stage: test
  script:
    - security-scan ./LibPing.Net.sln

deploy:
  stage: deploy
  script:
    - dotnet build -c Release --no-restore
    - dotnet pack LibPing.Net/LibPing.Net.csproj -c Release --no-restore -p:PackageVersion=0.0.8 -o .
    - ENTRYPOINT ["dotnet", "nuget", "push", "*.nupkg"]
    - CMD ["--api-key", $NUGET_API_KEY]
    #- nuget push \*.nupkg $NUGET_API_KEY
